name: Gitee repos mirror periodic job

on:
 push:
    branches:
        - dev
 schedule:
 # Runs at 01:00 UTC (9:00 AM Beijing) every day
        - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Single repo mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/cuizw911
          dst: gitee/Shangri-la/Sync_github_repo
          dst_key: ${{ secrets.SYNC_REPO_TO_GITEE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "Cui-Repo"